pipeline {
    agent any
    environment {
        KUBECONFIG = "/var/jenkins_home/.kube/config"
    }
	stages {
		stage('Clone repository') {
			steps {
				checkout scm
			}
		}
        
        stage('Helm Install') {
            steps {
                sh '''
                helm upgrade --install flask-app ./Track2_Step3/charts \
                  --namespace formazione-sou \
                  --set image.tag=latest
                '''
            }
        }
    }
}
